### ISSUE TITLE
in_class delay

### ISSUE THREAD

**Issue by TomEvin** [mckenziearts/laravel-notify#12]
Hello,

could you please add a variable to 'animate' config to manage the in_class delay before the animation start?

Thank you!

**Comment by ghost** [comment]
I know it's not organized, but I did the following on my forked version:

- Surrounded `.connectify-alert` class in `messages.blade.php` view with a `.connectify-container` class
- Added the following script to the same `if (session()->get('notify.model') === 'connect')` portion:
  ```
  <script>
      $(function() {
          $(".connectify-container")
              .hide()
              .fadeIn(500);
      });
  </script>
  ```
+ Optionally, and for consistency, run `npm run watch` then modify the `timeout()` methods in the `notify.js` file to have the same `500` timing instead of `200`.
