### ISSUE TITLE
Problem integrating this into a livewire controller

### ISSUE THREAD

**Issue by KangarooMusiQue** [mckenziearts/laravel-notify#26]
i try to integrate this into a livewire controller but dont get any resonse withing the function. 

I call it like: 

`   public function render()
    {
        notify()->success('Title was successfully rated.', 'Rating sucessfull');
        return view('livewire.infobarrating');
    }`

but no notification is rendered on the blade. 

what am i doing wrong?

**Comment by mckenziearts** [comment]
Let me see i didn't try yet with livewire

**Comment by pro-cms** [comment]
Hi got a simple solution, Just add @include('notify::messages') inside the livewire blade component and will work

**Comment by KangarooMusiQue** [comment]
This solutions only works if the laravel component is reloaded but if its only calling an action the notify windows stays forever in its corner and does not disappear. I would be very lucky if this will be implemented in a further version so that notifications work well with livewire components. Thank you and keep up the good work.

**Comment by ramonpego** [comment]
As @mckenziearts says here
https://github.com/mckenziearts/laravel-notify/issues/28#issuecomment-650508892
this package will not work as expected by Kangaroo, since it would have to be initialized by JS to work after a request made by livewire

First I **think** we would have to develop for it to also be initiated by JS
To then resolve this "integration"

**Comment by mckenziearts** [comment]
i think we need to create a livewire version. It cannot be implemented on this version. It is a package for notifications, we cannot force a user to install livewire if he does not intend to use it in his project.

**Comment by ramonpego** [comment]
I don't remember a package like yours working on the client side either
If it is, it will be an excellent resource, since we make some requests on the client side sometimes, and it would be nice to have them all the same
I currently use yours for when it comes from the server, and on the client I use sweet alert.
Livewire integration really has to be a bonus and not a requirement

It is a good idea to think about, when I have the time I am interested in looking and thinking about something to help. I really like the package

**Comment by mckenziearts** [comment]
For livewire you can try this package https://github.com/ascsoftw/livewire-toast
