### ISSUE TITLE
Destroying my Style and Js

### ISSUE THREAD

**Issue by hrace009** [mckenziearts/laravel-notify#84]
when i insert `@notifyCss` and `@notifyJs`, it will destroy my Style and Java Script, make my website not work at all.

please fix.

i am using tailwind 3.0 and alpine js

**Comment by kb6673** [comment]
The package loads Tailwind 2 & modern-normalize so there will be conflicts. 

See this -> https://github.com/mckenziearts/laravel-notify/issues/38

**Comment by SaedyMoz** [comment]
> The package loads Tailwind 2 & modern-normalize so there will be conflicts.
> 
> See this -> #38

It's better to  modify your style and codes based on your package.and remove styles that you never used in code.otherwise this package is useless.

**Comment by JoJo-Bear** [comment]
I made a PR #93 to fix at least some styling issue's that happened due to the preflight

**Comment by damms005** [comment]
I created [a fork that fixes collision with Alpine JS and all other possible style issues](https://github.com/damms005/laravel-notify).

I also updated the readme to make it easier to use this package, so that you won't have Javascript/CSS conflicts anymore.

For now, you simply use the fork by updating the `repositories` section of your `composer.json` file like so (or add it):

```
{
   "repositories": {
       ...
        "laravel-notify": {
            "type": "vcs",
            "url": "https://github.com/damms005/laravel-notify"
        }
    }
}
```

Hopefully, @mckenziearts will approve that I submit it as PR or effect my changes into this original package. Else, if people keep having these issues I may just make the new fork into its own new separate package and continue to try and maintain it and make it friendlier to use, because IMHO, this package is too awesome to have such a poor DX.

The authors have done an outstanding job and kudos to them!

**EDIT**:
[As noted](https://github.com/mckenziearts/laravel-notify/issues/84#issuecomment-1124663917) by @JoJo-Bear,  his [PR](https://github.com/mckenziearts/laravel-notify/pull/93) only fixed the style/Tailwind issue. The javascript issue (as contained in this issue's title) still persists, and I strongly believe that the definitive fix will be the approach described in my comment about my fork above. 
cc @mckenziearts

**Comment by EriksonEnterprises** [comment]
> I created [a fork that fixes collision with Alpine JS and all other possible style issues](https://github.com/damms005/laravel-notify).
> 
> I also updated the readme to make it easier to use this package, so that you won't have Javascript/CSS conflicts anymore.
> 
> For now, you simply use the fork by updating the `repositories` section of your `composer.json` file like so (or add it):
> 
> ```
> {
>    "repositories": {
>        ...
>         "laravel-notify": {
>             "type": "vcs",
>             "url": "https://github.com/damms005/laravel-notify"
>         }
>     }
> }
> ```
> 
> Hopefully, @mckenziearts will approve that I submit it as PR or effect my changes into this original package. Else, if people keep having these issues I may just make the new fork into its own new separate package and continue to try and maintain it and make it friendlier to use, because IMHO, this package is too awesome to have such a poor DX.
> 
> The authors have done an outstanding job and kudos to them!
> 
> **EDIT**: [As noted](https://github.com/mckenziearts/laravel-notify/issues/84#issuecomment-1124663917) by @JoJo-Bear, his [PR](https://github.com/mckenziearts/laravel-notify/pull/93) only fixed the style/Tailwind issue. The javascript issue (as contained in this issue's title) still persists, and I strongly believe that the definitive fix will be the approach described in my comment about my fork above. cc @mckenziearts

Unfortunately this still doesn't work with Bootstrap :/
